let weathercode = new Map();

weathercode.set(0, './img/day.svg');
weathercode.set(1, './img/cloudy-day-1.svg');
weathercode.set(2, './img/cloudy-day-3.svg');
weathercode.set('0N', './img/night.svg');
weathercode.set('1N', './img/cloudy-night-1.svg');
weathercode.set('2N', './img/cloudy-night-3.svg');
weathercode.set('3N', './img/cloudy.svg');
weathercode.set(3, './img/cloudy.svg');
weathercode.set(45, './img/cloudy.svg');
weathercode.set(61, './img/rainy-4.svg');
weathercode.set(63, './img/rainy-5.svg');
weathercode.set(65, './img/rainy-6.svg');
weathercode.set(80, './img/rainy-4.svg');
weathercode.set(81, './img/rainy-5.svg');
weathercode.set(82, './img/rainy-6.svg');
weathercode.set(95, './img/thunder.svg');
weathercode.set('95N', './img/thunder.svg');
weathercode.set(96, './img/thunder.svg');
weathercode.set('96N', './img/thunder.svg');
weathercode.set('45N', './img/cloudy.svg');
weathercode.set('61N', './img/rainy-4.svg');
weathercode.set('63N', './img/rainy-5.svg');
weathercode.set('65N', './img/rainy-6.svg');
weathercode.set('80N', './img/rainy-4.svg');
weathercode.set('81N', './img/rainy-5.svg');
weathercode.set('82N', './img/rainy-6.svg');
export default weathercode;